### ISSUE TITLE
Strange characters in editor of Xcode

### ISSUE THREAD

**Issue by ikait** [adobe-fonts/source-han-code-jp#8] opened 2015-11-09 05:09 UTC
Just after setting font to Source Han Code JP, it seems OK:
<img width="865" alt="screen shot 2015-11-09 at 14 00 34" src="https://cloud.githubusercontent.com/assets/1997960/11026263/531b2406-86ea-11e5-82a5-613aa6c6e412.png">

But when I once closed and opened Xcode:
<img width="904" alt="screen shot 2015-11-09 at 13 54 34" src="https://cloud.githubusercontent.com/assets/1997960/11026199/75de4fb4-86e9-11e5-8307-5f76021e0213.png">

My guess is that 全角 (full-width) characters are used. What can I fix this?
- Xcode Version 7.1 (7B91b)
- OS X El Capitan 10.11.1 (15B42)

Thanks

**Comment by hatchzo** [comment] 2015-11-09 10:55
I can see the same thing on my machine, and the appearance will be corrected that you select "Osaka" on the preference and then select the previous font again. This problem is reproduced not only by Source Han Code JP, but also Hiragino, Source Han Sans or even TTF font like as Meiryo. I believer this is Xcode issue.

**Comment by kenlunde** [comment] 2015-11-09 13:42
Given what @hatchzo wrote, specifically that this issue occurs with other fonts, it is definitely an issue with Xcode. I wonder whether the 'fwid' GSUB feature is being inadvertently invoked. A good way to find out would be to build an experimental version of one of these fonts with that GSUB feature removed.

**Comment by ikait** [comment] 2015-11-10 02:04
@hatchzo Thank you for your knowledge. I saw it reproduced by other fonts such as Hiragino Sans. As @kenlunde taught me, I removed around fwid from `./features_sub_gsub.JP`, rebuild and reinstalled. Now it works well! (https://github.com/ikait/source-han-code-jp/commit/03f0ed254210510f193be5a80bf9e6f45f346b44#diff-72134ec72dabd6b9b6bd18434370583a)
Thank you.

**Comment by kenlunde** [comment] 2015-11-10 02:05
👍

@hatchzo: You might consider removing the 'fwid' GSUB feature, especially given that the glyphs that it affects are also directly encoded.

**Comment by kenlunde** [comment] 2015-11-10 02:14
@ikait: BTW, I still consider that it is a bug for Xcode to invoke the 'fwid' GSUB feature. Is the Xcode [this](https://itunes.apple.com/us/app/xcode/id497799835?mt=12) one?

**Comment by ikait** [comment] 2015-11-10 03:02
@kenlunde Yes it is, but newer version (7.1.1) is released yesterday. I saw the bug on only 7.1. sorry

**Comment by kenlunde** [comment] 2015-11-10 03:08
@ikait Do you know whether this issue was fixed in Version 7.1.1? In any case, I reported this issue to our friends at Apple.

**Comment by ikait** [comment] 2015-11-10 03:14
@kenlunde sorry but I don't. I guess this issue wasn't fixed because of no description about the editor in release note.

> Xcode 7.1.1 improves stability and fixes critical issues in Interface Builder, debugging, and UI testing.
> https://itunes.apple.com/us/app/xcode/id497799835?mt=12

**Comment by kenlunde** [comment] 2015-11-10 03:16
Thank you for the clarification. 明らかにすること、ありがとうございました。

**Comment by hatchzo** [comment] 2015-11-10 03:57
Some users have complained about this issue since Source Han Code JP was released. I think removing fwid' GSUB feature is one possibility to resolve it.

**Comment by kenlunde** [comment] 2015-11-10 04:00
@hatchzo As I conveyed to you privately, almost all of the glyphs that are made accessible via the 'fwid' GSUB feature are also encoded, so removing this GSUB feature seems like a Very Good Idea™ to me.

**Comment by hatchzo** [comment] 2015-11-10 04:37
OK, I will do that.

**Comment by hatchzo** [comment] 2015-12-01 04:23
I believe that this issue is fixed in Source Han Code JP v2.000.

**Closed as completed by hatchzo** 2015-12-01 04:23 UTC
Labels: Not This Product
